
require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: disable
  TargetRubyVersion: 3.1

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/DescribeClass:
  Enabled: false

RSpec/SharedContext:
  Enabled: false
